-- AlterTable
ALTER TABLE "books" ADD COLUMN     "publishYear" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "ratings" DECIMAL(2,1) NOT NULL DEFAULT 0.0,
ADD COLUMN     "weight" DECIMAL(10,2) NOT NULL DEFAULT 0.0;
